-- QMIND 2026 project-table recovery script.
-- Safe to re-run: existing rows are matched by project title. Existing ids,
-- images, GitHub links, and PM login emails are preserved.

begin;

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  "projectTitle" text,
  tags text[] not null default '{}'::text[],
  category text,
  "githubUrl" text not null default '',
  "projectImages" text[] not null default '{}'::text[],
  "shortDescription" text,
  "impactDescription" text,
  "fullDescription" text,
  "pmEmail" text not null default '',
  published boolean not null default false,
  year integer default 2026,
  "projectManagers" text[] not null default '{}'::text[],
  "facultyAdvisor" text,
  "facultyAdvisorUrl" text,
  is_hiring boolean not null default true
);

alter table public.projects
  add column if not exists "projectManagers" text[] not null default '{}'::text[],
  add column if not exists "facultyAdvisor" text,
  add column if not exists "facultyAdvisorUrl" text,
  add column if not exists is_hiring boolean not null default true;

create table if not exists public.hiring_project_prompts (
  project_id bigint primary key references public.projects(id) on delete cascade,
  prompt_text text,
  video_url text
);

alter table public.hiring_project_prompts
  add column if not exists prompt_text text,
  add column if not exists video_url text;

alter table public.hiring_project_prompts
  alter column prompt_text drop not null;

grant select on public.projects to anon, authenticated;
grant select on public.hiring_project_prompts to anon, authenticated;

alter table public.projects enable row level security;
alter table public.hiring_project_prompts enable row level security;

drop policy if exists "Recovery public project read" on public.projects;
create policy "Recovery public project read"
on public.projects for select
to anon, authenticated
using (
  published = true
  or (auth.role() = 'authenticated' and "pmEmail" = auth.email())
);

drop policy if exists "Recovery published hiring prompt read" on public.hiring_project_prompts;
create policy "Recovery published hiring prompt read"
on public.hiring_project_prompts for select
to anon, authenticated
using (
  exists (
    select 1
    from public.projects
    where projects.id = hiring_project_prompts.project_id
      and projects.published = true
      and projects.is_hiring = true
      and projects.category in ('Consulting', 'Research')
  )
);

do $$
declare
  project_data record;
  seed_project_id bigint;
begin
  for project_data in
    select *
    from (values
      (
        'Vehicle Telematics Modelling'::text,
        array['vehicle telematics', 'sensor data', 'signal processing', 'machine learning', 'applied AI']::text[],
        'Consulting'::text,
        'Build machine learning models that answer practical questions about how vehicles and telematics devices are moving.'::text,
        'Use real vehicle sensor and engine data to infer reversing, installation quality, and device orientation in messy real-world conditions.'::text,
        $vehicle$Geotab builds the GO device: a small unit that plugs into a vehicle and streams data about how that vehicle is moving — GPS, motion sensors, and information straight from the engine. Millions of them are on the road.

This team will build machine learning models that answer questions that sound simple but aren''t:

• Is this vehicle currently reversing?
• Was this device installed properly?
• Which way is the device actually facing inside the vehicle?

The last one matters more than you''d expect. Nobody installs these at a consistent angle, so the device doesn''t know which direction is “forward” until it figures that out from the data — and the first two questions can''t be answered until it does. Add in the fact that a truck might be sitting on a hill, and the sensor readings you''d expect to be obvious stop being obvious.

Geotab is providing physical devices and real production data, and an engineer from their automotive team will meet with the group weekly. You''ll be working on a problem their engineers actually care about, with their input along the way.

Good fit if you''re interested in sensor data, signal processing, or applied ML on messy real-world inputs.$vehicle$,
        array['James Cawse']::text[],
        null::text,
        null::text,
        $prompt$What experience do you have in building projects and using AI?$prompt$,
        null::text
      ),
      (
        'Backboard OpenSource CLI Development'::text,
        array['AI agents', 'TypeScript', 'Bun', 'open source', 'developer tools']::text[],
        'Consulting'::text,
        'Contribute to an open-source terminal agent for AI-assisted software development.'::text,
        'The project offers hands-on experience with agent orchestration, MCP and skills integrations, permissions, checkpoints, testing, CI, and browser automation in a public TypeScript and Bun codebase.'::text,
        $backboard$The Company Backboard builds infrastructure for AI coding agents, for teams who want serious control over their models, memory, and deployment instead of being locked into one vendor''s black box. Think enterprise-grade AI dev tooling: cloud, private cloud, or fully air-gapped.

The Tool: R-CLI is Backboard''s open-source terminal agent (TypeScript + Bun). Drop it into a project, tell it what you want done, and it reads files, edits code, runs commands, and tests its own changes, with checkpoints and undo/redo so nothing gets wrecked. It''s model-agnostic (Anthropic, OpenAI, Google, OpenRouter), extensible via MCP servers and skills, and it''s already competitive on public coding benchmarks.

The Work: Contributors will dig into the actual codebase:
• Core agent engine — the TypeScript/Bun internals that power file editing, command execution, and reasoning.
• MCP and skills integrations — expanding what tools and workflows the agent can plug into.
• Permissions and checkpoints — the safety rails that let users trust an AI touching their code.
• Testing and CI — lint, typecheck, test suite, and benchmarking.
• Browser/computer-use automation — the experimental frontier of what the agent can control.

This is agentic AI, the single hottest area in software right now, and it''s a live public repo, so every commit is a portfolio piece.

Who We''re Looking For: Builders who want to work inside a real TypeScript codebase, not a toy repo; people curious about how AI agents actually work under the hood — reasoning, tool use, and context management; detail-oriented types who''d enjoy owning the permissions/safety layer or the test suite; anyone who likes tinkering with integrations (MCP servers, skills, and new tool support); and people who want a public GitHub trail of real contributions to point to for co-op, internships, or full-time roles.$backboard$,
        array['Mukesh Royal', 'Shaanvir Singh']::text[],
        null::text,
        null::text,
        null::text,
        null::text
      ),
      (
        'Quadcopter Drone Computer Vision'::text,
        array['computer vision', 'drones', 'Jetson', 'obstacle avoidance', 'robotics']::text[],
        'Consulting'::text,
        'Develop real-time computer vision for obstacle avoidance on a flying quadcopter.'::text,
        'In collaboration with ARA Robotics, the project will use a camera and onboard Jetson computing to help a quadcopter perceive and navigate its surroundings without lidar.'::text,
        $quadcopter$We''re giving eyes to a quadcopter drone. One camera, no lidar, real-time obstacle avoidance running live on a Jetson mid-flight. The pipeline involves a model interpreting visual input to determine depth of objects in its surroundings, and converting this depth map into actionable controls. We will distill the current state-of-the-art depth model (Depth Anything V2) down to a smaller custom CNN light enough to be run onboard in real-time. To support this mission, we''re collaborating with the experts over at ARA Robotics who develop drone technology and apply it to real-world problems here in Canada. We''ve got the hardware, looking for the right human brains to make it fly.$quadcopter$,
        array['Jake Feldman Starosta']::text[],
        null::text,
        null::text,
        $prompt$What ethical role do technologists play in how their creations get used, versus the people who deploy them? How do you think we should approach developing dual-use technologies, such as drones and AI?$prompt$,
        null::text
      ),
      (
        'DCP Federated Learning'::text,
        array['federated learning', 'machine learning', 'JavaScript', 'TypeScript', 'healthcare']::text[],
        'Consulting'::text,
        'Build a proof-of-concept federated learning package on DCP so hospitals can train a shared machine-learning model without sharing private data.'::text,
        'The initial application is predicting treatment response to biologics for psoriatic arthritis. The package will be publicly released as open source, and the project offers hands-on experience researching ML models and implementing federated learning techniques.'::text,
        $dcp$In partnership with Distributive, a Kingston-based distributed computing development company, we are building a proof-of-concept package that lets people run federated learning on top of DCP (Distributive''s compute-sharing platform). This package will enable multiple hospitals to train one shared Machine Learning model together, without ever having to share their private data with each other, or with us. Initial application focus is predicting treatment response to biologics for psoriatic arthritis. This project will give you hands-on experience researching ML models and implementing federated learning techniques. The package we produce will be made publicly available once it''s completed, contributing to the open-source ML ecosystem. We''ll likely be building this in JavaScript/TypeScript, so experience with either will come in handy!$dcp$,
        array['Nate Cheung', 'Theo Leone']::text[],
        null::text,
        null::text,
        $prompt$Describe a project you recently worked on that you feel passionate about.$prompt$,
        null::text
      ),
      (
        'Conversational Intelligence for Advanced Process Control'::text,
        array['conversational AI', 'natural language', 'process control', 'mining', 'explainability']::text[],
        'Consulting'::text,
        'Explore a conversational AI framework that explains complex Advanced Process Control behaviour to engineers and operators in mineral processing.'::text,
        'The framework will combine process data, controller information, and operational knowledge to produce clear, evidence-based explanations that support better operational decisions.'::text,
        $woodgrove$Built in collaboration with Woodgrove Technologies, a mining and mineral processing company based in Toronto, this project explores a conversational AI framework for Advanced Process Control systems used in mineral processing. The framework will bring together process data, controller information, and operational knowledge to help explain complex plant behaviour and controller actions.

These systems automate complex decisions across processes such as grinding, flotation, and separation, but often provide limited visibility into why certain actions are taken. The goal is to use AI to turn this complex and fragmented information into clear, evidence-based natural language explanations, helping engineers and operators better understand system behaviour and make more informed decisions.$woodgrove$,
        array['Ryanjeet Gill', 'Evan Johnstone']::text[],
        null::text,
        null::text,
        $prompt$Tell us what motivates you, and how that motivation has pushed you to create opportunities for yourself and pursue new challenges or learning experiences.$prompt$,
        'https://drive.google.com/file/d/1w2u7Qo4D8XUKe9Jr2GRI3VGITfo8BY5m/view?usp=sharing'::text
      ),
      (
        'TrustLayer'::text,
        array['responsible AI', 'evaluation', 'LLMs', 'AI agents', 'safety']::text[],
        'Consulting'::text,
        'Develop a responsible AI evaluation system that assesses AI-generated outputs and actions before they enter real-world workflows.'::text,
        'The team will evaluate reliability, fairness, safety, and the need for human review while working with industry partners to shape the system around a real responsible-AI challenge.'::text,
        $trustlayer$This project will develop a responsible AI evaluation system designed to assess AI-generated outputs or actions before they are used in real-world workflows. As organizations increasingly rely on LLMs and AI agents, unreliable, biased, unsafe, or unsupported outputs can become difficult to catch before they affect users or downstream decisions. The project''s initial direction is to build a flexible evaluation and quality-assurance layer that can assess factors such as factual reliability, fairness, safety, and whether human review is required. The team will also work with industry partners early in the project to identify a real responsible AI challenge and refine the final system around the needs of the selected client.$trustlayer$,
        array['Reyan Seghal']::text[],
        null::text,
        null::text,
        $prompt$Tell us about a time you had to solve a problem where the answer or path forward was not immediately clear. How did you approach it, what factors did you consider, and how did you decide what to do?$prompt$,
        null::text
      ),
      (
        'AI Agent Integration'::text,
        array['AI agents', 'governance', 'business strategy', 'traceability', 'security']::text[],
        'Consulting'::text,
        'Build a governed AI platform that enables intelligent agents to support complex business work and informed decision-making.'::text,
        'Working with Electric Mind, the team will create a reliable, traceable, and secure foundation for agents that analyze business problems and coordinate information across an organization.'::text,
        $electric$Due to the confidential nature of the client, this description is abridged.

Working with Electric Mind, a consulting firm in downtown Toronto, to develop a governed AI platform that enables intelligent agents to support complex business work. The project focuses on building a reliable and scalable foundation for AI, with agents designed to analyze complex business problems, coordinate information across different areas of an organization, and support informed decision-making and strategic recommendations. The team will focus on building a reliable and scalable foundation for AI, working with the Electric Mind team to integrate AI tools in high impact fields, ensuring accuracy, traceability, and security.$electric$,
        array['Elizabeth Bighiu', 'Eitan Zur']::text[],
        null::text,
        null::text,
        $prompt$Share a project you have worked on that you are most proud of. Explain the goal of your project and your role within it.$prompt$,
        null::text
      ),
      (
        'ScamBench AI Recruitment Phishing'::text,
        array['cybersecurity', 'phishing', 'deepfakes', 'human behaviour', 'experiments']::text[],
        'Research'::text,
        'Study how AI-generated recruiter profiles and deepfakes influence trust and security decisions during multi-step remote job scams.'::text,
        'In collaboration with Menlo Park Intelligence, the project will use a two-stage recruitment experiment to measure compliance, hesitation, and the effects of visual fidelity on later scrutiny.'::text,
        $scambench$Generative AI has fueled a massive spike in remote job scams, yet current security tools fail to address how human judgment breaks down during multi-step deceptions. It remains unclear if early trust in a synthetic recruiter profile causes victims to drop their guard, or if a deepfake''s visual quality matters more than the mere presence of professional branding. In collaboration with Menlo Park Intelligence, a research organization led by Fred Heiding, Research Fellow at UC Berkeley, this project uses a remote, two-stage recruitment experiment with varying AI visual fidelity. By tracking compliance and hidden metrics like hesitation, we will isolate whether early trust reduces later scrutiny, providing the foundational data needed to design better cybersecurity defenses.$scambench$,
        array['Michelle Kelly', 'Basma Azeem']::text[],
        null::text,
        null::text,
        $prompt$Pick One:

Walk us through a time you had to adjust a project plan midway through because something wasn''t working.

How do you decide whether a source is trustworthy when you''re researching something outside your expertise?$prompt$,
        null::text
      ),
      (
        'Beyond AUROC: Clinical Readiness of ED Chest-Pain AI'::text,
        array['healthcare', 'clinical AI', 'emergency medicine', 'machine learning', 'evidence review']::text[],
        'Research'::text,
        'Evaluate what evidence is needed before chest-pain AI models can be trusted in real emergency-department decisions.'::text,
        'Beyond AUROC will assess calibration, safety of decision thresholds, generalizability, and workflow fit before shaping a feasible MIMIC-IV benchmark, subject to access and linkage feasibility.'::text,
        $auroc$Faculty Supervisor: Dr. Venkatesh Thiruganasambandamoorthy
https://ohri.ca/en/find-researcher/venkatesh-thiruganasambandamoorthy

Can an AI model look excellent on paper and still be unready for the bedside? This project asks what evidence is needed before a chest-pain model can be trusted in real emergency-department decisions.

Emergency clinicians must identify acute coronary syndrome quickly while avoiding unnecessary admission, prolonged observation, and testing for lower-risk patients. AI and machine-learning models may help, but a high area under the receiver operating characteristic curve (AUROC) only shows discrimination. It does not establish that predicted risks are accurate, thresholds are safe, results generalize, or the model fits the clinical workflow.

Beyond AUROC will update the evidence on AI/ML models used for diagnosis, short-term coronary prognosis, and coronary-risk-informed disposition in adults presenting to the ED with chest pain or suspected ACS. The review will evaluate clinical readiness using current prediction-model guidance. Its findings will then shape a feasible, workflow-constrained benchmark using MIMIC-IV data, subject to access and linkage feasibility.$auroc$,
        array['Bramleen Papneja']::text[],
        'Dr. Venkatesh Thiruganasambandamoorthy'::text,
        'https://ohri.ca/en/find-researcher/venkatesh-thiruganasambandamoorthy'::text,
        $prompt$AI models can perform well on paper but still be difficult to trust in real clinical settings. What do you think is the biggest challenge in closing that gap? Explain how you would approach it and what skills or experiences you would bring to the team.$prompt$,
        null::text
      ),
      (
        'LLM-Enhanced Decision Making Agents for Cloud Autoscaling'::text,
        array['LLMs', 'cloud computing', 'autoscaling', 'systems', 'decision-making']::text[],
        'Research'::text,
        'Explore whether large language models can improve dynamic cloud resource management through context-aware autoscaling decisions.'::text,
        'The research will evaluate when LLM-based reasoning adds value against traditional threshold and control-policy methods, including trade-offs in performance, resource efficiency, and adaptability.'::text,
        $autoscaling$This project explores the use of large language models as intelligent decision-making agents for dynamic cloud resource management. We will develop an LLM-enhanced autoscaling controller that interprets real-time system telemetry such as CPU utilization, request traffic, response latency, and resource availability to determine when and how cloud resources should be scaled.

By integrating contextual information and operational objectives alongside traditional system metrics, the controller aims to make more informed and adaptable scaling decisions. Traditional cloud autoscaling methods typically rely on predefined thresholds or control policies that react to changes in system utilization. While effective, these approaches have limited ability to incorporate higher-level context or adapt their decision-making strategy to unfamiliar conditions. Our research will examine under what conditions LLM-based reasoning provides meaningful value, while evaluating trade-offs in system performance, resource efficiency and adaptability.$autoscaling$,
        array['Daryan Fadavi']::text[],
        null::text,
        null::text,
        $prompt$What is something you have gone down a rabbit hole learning about recently?$prompt$,
        null::text
      ),
      (
        'Uncertainty-Aware Deep Learning for Parkinsonian Motor Symptom Severity Estimation from Monocular Video'::text,
        array['computer vision', 'deep learning', 'healthcare', 'uncertainty', 'fairness']::text[],
        'Research'::text,
        'Use monocular video and uncertainty-aware deep learning to estimate Parkinsonian motor symptom severity while communicating when the model is unsure.'::text,
        'The project combines pose estimation, temporal modelling, explainability, fairness, and human oversight to explore more transparent and responsible clinical decision support.'::text,
        $parkinson$Faculty Supervisor: Dr. Gavin Winston

Rather than producing a binary prediction of whether a patient has Parkinson''s disease, this project explores computer vision for uncertainty-aware assessment of Parkinson''s motor symptoms from monocular video. Using pose estimation and temporal deep learning, the model would quantify movement patterns and estimate motor symptom severity while communicating how uncertain it is in its predictions, such as through confidence or prediction intervals. The project will also examine the ethical implications of using AI for neurological assessment, including whether model performance and uncertainty differ across patient populations, how potential biases in training data may affect predictions, and when an AI system should defer to clinician judgement rather than provide an assessment. By integrating uncertainty, explainability, fairness, and human oversight into model evaluation, the project aims to explore how computer vision systems can provide more transparent, reliable, and ethically responsible support for clinical decision-making.$parkinson$,
        array['Wendy Zhang', 'Jason Chen']::text[],
        'Dr. Gavin Winston'::text,
        null::text,
        $prompt$When developing an AI system for a real-world application, what factors should a team consider beyond achieving high model accuracy? Choose one or two factors you think are most important and explain why.$prompt$,
        null::text
      ),
      (
        'CanopyMap'::text,
        array['agricultural technology', 'computer vision', 'image segmentation', 'indoor farming', 'automation']::text[],
        'Research'::text,
        'Use computer vision to measure plant growth in indoor farms and help automate growth-optimization decisions.'::text,
        'CanopyMap addresses the lack of high-quality training data for indoor agriculture by applying existing segmentation models to camera data from an aeroponic farm.'::text,
        $canopy$Faculty Advisor: Dr. Christian Muse

Two of the biggest pain points for agricultural tech and a barrier to automation is measuring plant growth and obtaining quality training data at a large scale. Farming environments can vary a lot and the hardware that is used to monitor such environments can often be in very different conditions which makes adapting a single model to different environments very challenging.

Lots of research papers cover outdoor farming, very few try to fix the gap in training data for indoor environments. That''s what we''re trying to fix with CanopyMap. We have access to an aeroponic farm with lots of cameras. We are going to use existing models to run image segmentation on the plants and using that try to measure the plant growth over time. This will eventually help the farm automate its growth optimization algorithm.$canopy$,
        array[]::text[],
        'Dr. Christian Muse'::text,
        null::text,
        $prompt$Teach me about a concept/skill that you are very passionate about in a minute or two. Could be anything, as long as you can make me feel like I know a lot about it at the end without actually overloading me with information.$prompt$,
        null::text
      ),
      (
        'Mechanistic Interpretability of Test-Time Reasoning in Large Language Models'::text,
        array['mechanistic interpretability', 'LLMs', 'AI safety', 'sparse autoencoders', 'open source']::text[],
        'Research'::text,
        'Build an interpretability toolkit to investigate the internal circuits behind uncertainty, branching, premise commitment, and error recovery in reasoning models.'::text,
        'The team will use sparse autoencoders and causal interventions on models such as Qwen-2.5-Math and DeepSeek-R1-Distill to develop open-source tools and a diagnostic benchmark for AI safety research.'::text,
        $mechanistic$Ever wondered what''s actually happening inside a reasoning model when it “thinks”?

Modern reasoning models like GPT-5, Gemini 3, and Deepseek-R1 don''t just spit out an answer, they burn extra compute at inference time, generating long chains of intermediate steps before committing to a final response. This “test-time reasoning” is why they''re so good at math, logic, and multi-step problems. But we only ever watch this process from the outside, reading the output tokens as a model branches, backtracks, or corrects itself. Nobody actually knows what''s happening under the hood when it does.

Worse, these models'' most dangerous failures aren''t hesitant guesses; they''re confident, fluent, perfectly-structured chains of reasoning that are just wrong. And the tools we use to catch uncertainty during test-time reasoning, like token entropy, are blind to this exact failure mode, because a confidently wrong model doesn''t look uncertain at all.

We''re building a mechanistic interpretability toolkit for test-time reasoning itself. Using sparse autoencoders, the same technique Anthropic used to find interpretable features inside Claude, we''re going to crack open models like Qwen-2.5-Math and DeepSeek-R1-Distill while they reason, and find the actual internal circuits behind uncertainty, branching, premise commitment, and error recovery as they unfold step by step. Then we''re not just going to observe these features, we''re going to causally test them: amplify them, suppress them, and see if we can steer a model toward catching its own mistakes mid-chain, before they cascade into a wrong answer.

This is a research team building real infrastructure (SAELens, TransformerLens, Circuit Tracer), targeting a workshop paper and a top-venue submission. You''ll get hands-on experience in one of the most in-demand, least-taught areas of AI safety research, the kind of work that''s usually locked inside frontier labs, while actually shipping open-source tools and a diagnostic benchmark the community can use.

If you want to stop treating language models as black boxes and start finding out what''s really going on inside them while they think, this is the project.$mechanistic$,
        array['Kevin Wang', 'Rastin Aghighi']::text[],
        null::text,
        null::text,
        $prompt$What risks from AI are you most concerned about, and why?$prompt$,
        null::text
      ),
      (
        'Task-Differentiated EEG Hyperscanning'::text,
        array['EEG', 'hyperscanning', 'neuroscience', 'machine learning', 'teamwork']::text[],
        'Research'::text,
        'Investigate how distinct team roles influence neural synchronization during collaborative problem-solving.'::text,
        'The project combines experimental neuroscience and EEG machine learning to study neural coordination in realistic teamwork settings.'::text,
        $eeg$We are investigating EEG Hyperscanning: how two individuals'' brain waves synchronize during social interactions. Our framework aims to replicate realistic team settings by assigning participants distinct tasks but a shared goal — diffusing a virtual bomb. This procedure will inform our understanding of how neural synchronization potentially enables social teamwork.

In typical hyperscanning paradigms, we measure neural synchronization on participants who are completing identical tasks. This design has two main limitations we seek to address: (1) it applies poorly to most team settings, since team members tend to differ in tasks; (2) by giving identical tasks, participants are exposed to similar sensory stimuli. When studying the effects of cognitive teamwork on neural synchronization, shared sensory stimuli causes an issue where we cannot tell if the observed effects are due to cognition or sensation. By implementing distinct tasks, we increase our confidence that the observed synchronization is (1) reflective of real-world teamwork; (2) caused by cognitive synchronization.

We are aiming to make two sub-teams within our project, which each require different skill sets. The Research Team will complete literature reviews, write the paper, and run participants through the experimental procedure, and the Coding Team will pre-process and analyze EEG data using machine learning. Both teams will work together to create the experimental procedure to maximize ease of data collection and ability to fill gaps in the literature, as described above. For the Research Team, we want individuals who are adept at reading scientific literature, scientific writing and instructing participants through a procedure. For the Coding Team, we want individuals who have strong coding fundamentals — no previous AI or machine learning experience is needed. Experience with MATLAB, EEG, and EEGLAB is appreciated!$eeg$,
        array['Ashleigh Cunningham', 'Benjamin Craig-Browne']::text[],
        null::text,
        null::text,
        null::text,
        'https://drive.google.com/file/d/1lqYLEhB1AStXw91M53gwejinW-5Hxs4I/view?usp=sharing'::text
      ),
      (
        'Wildfire Discovery Drone'::text,
        array['computer vision', 'wildfire detection', 'drones', 'thermal imaging', 'sensor fusion']::text[],
        'Research'::text,
        'Develop a high-precision drone, sensor, and satellite-validation system for early wildfire detection.'::text,
        'The team will combine thermal imaging, gas sensing, onboard computing, MATLAB analysis, and satellite data to improve wildfire monitoring and prevention.'::text,
        $wildfire$Under the supervision of Dr. Siddiqui and Dr. Asad, this project is developing a high-precision, drone-based wildfire detection and satellite validation system!

The team is operating RCMP commercial-grade drones, provided and piloted by professionals at the Royal Military College of Canada, equipped with a FLIR A700-series thermal camera (a $30,000+ research-grade radiometric imaging system) alongside CO, CO₂, and CH₄ gas sensors to capture fine-scale emission and heat signatures over high-risk areas such as farmland. The platform runs a distributed onboard computing architecture: an NVIDIA Jetson handles real-time thermal image acquisition and processing, while a Raspberry Pi 5 manages synchronized gas-sensor data collection, with all streams analyzed in MATLAB. By calibrating UAV measurements against ground-truth sensors and satellite data from sources like NASA, the project aims to validate and correct satellite wildfire detection with sub-pixel precision, transforming early detection into a powerful tool for prevention.$wildfire$,
        array['Viona Hashemkhani']::text[],
        'Dr. Siddiqui and Dr. Asad'::text,
        null::text,
        $prompt$Tell me an interesting story about yourself.$prompt$,
        null::text
      ),
      (
        'Diffusion-Model Rendering for Re-Themable Games'::text,
        array['diffusion models', 'computer vision', 'game development', 'real-time rendering', 'generative AI']::text[],
        'Research'::text,
        'Investigate whether a small diffusion renderer can compose unseen visual attribute combinations in interactive game scenes.'::text,
        'The project will test how dataset design, model capacity, and architecture affect controllable generative game rendering under realistic research constraints.'::text,
        $diffusion$Recent work has demonstrated that diffusion models can serve as interactive game renderers, generating each frame conditioned on game state rather than rasterizing hand-built assets. Existing systems, however, either render a single fixed visual style or achieve open-ended visual control only through datasets of a scale far beyond the reach of most research budgets. This project investigates the intermediate question: whether a small diffusion renderer, trained on a densely factored dataset, can compose visual attributes it has seen into combinations it has not. To make that question tractable, the team will construct a custom Doom-style ray-cast engine and a deterministic skinning pipeline, giving full control over the structure of the training data and the design of held-out combinations. Success would provide early evidence that the approach scales; failure would distinguish capacity-bound from architecture-bound limitations, which is itself a useful and reportable result.

Members will work across four streams — engine and rendering, data pipeline design, diffusion model architecture and training, and evaluation and representational analysis — with deliverables including the engine, the data generation pipeline, a trained conditional renderer, and a full account of the findings. The project is supported by $10,000 in funding from Chatforce and is supervised by Robert Ciborowsko.

Further Project Details: https://drive.google.com/file/d/1tptag4-g5bOo2qjKrx6eM_tjnsjF2ngQ/view?usp=sharing$diffusion$,
        array['Matthew Lones']::text[],
        'Robert Ciborowsko'::text,
        null::text,
        $prompt$Tell me what your passion for AI comes from. What are your goals and why do you pursue them?$prompt$,
        null::text
      ),
      (
        'Visibility Thresholds: The Shape a Thought Needs'::text,
        array['vision-language models', 'CLIP', 'generative models', 'PyTorch', 'interpretability']::text[],
        'Research'::text,
        'Study when CLIP similarity scores correspond to genuinely grounded visual concepts rather than abstract numerical matches.'::text,
        'The project will compare pixel, Fourier, and differentiable-vector substrates to identify when coherent images emerge from CLIP-guided optimization.'::text,
        $visibility$The project asks a simple question: when CLIP reports high similarity between a text concept and an image, does the model actually see the concept? We test this by dreaming: generating images that maximize CLIP''s similarity score for a given word, then looking at what actually appears. If the concept is genuinely grounded, the image should look like something. If it isn''t, the score is just a number.

We run this across progressively constrained image substrates (raw pixels, Fourier bases, differentiable vector strokes) to find the point where coherent images start to emerge.

Team members will work in Google Colab with PyTorch and CLIP. No prior experience with vision-language models is required, but you should be comfortable with Python and willing to think about what these models are actually doing.

The attached image shows our baseline results from raw pixel dreaming. Notice how abstract concepts are much harder to “dream” than concrete ones!$visibility$,
        array['Armita Afroushe']::text[],
        null::text,
        null::text,
        null::text,
        null::text
      ),
      (
        'Benchmarking RAG Systems for Patient Timeline Reasoning'::text,
        array['RAG', 'GraphRAG', 'healthcare', 'clinical NLP', 'evaluation']::text[],
        'Research'::text,
        'Compare retrieval-augmented generation systems on questions that require reasoning across a patient''s medical timeline.'::text,
        'The project will evaluate when vector, metadata-based, GraphRAG, and temporal GraphRAG systems retrieve and use evidence correctly while avoiding privacy risks with synthetic patient data.'::text,
        $rag$This project explores how different RAG systems perform when answering questions about a patient''s medical history over time. Instead of focusing on general medical questions, we will look at patient timeline questions that may require connecting information across visits, symptoms, medications, lab results, and doctor''s notes.

We will compare retrieval methods such as basic vector RAG, metadata-based RAG, GraphRAG, and temporal GraphRAG. The goal is to understand when a more complex system is actually useful, and when a simpler system is enough.

The project will likely use synthetic patient data, such as Synthea, to avoid privacy concerns while still working with realistic-style patient histories. We will evaluate both whether the system finds the right evidence and whether it uses that evidence correctly.

By the end, we hope to identify which RAG approaches work best for different types of patient-history questions, such as tracking progression, checking treatment response, handling conflicting records, or deciding when there is not enough evidence to answer.$rag$,
        array['Ashmaan Soheil']::text[],
        null::text,
        null::text,
        $prompt$Describe a time you had to choose between multiple possible approaches to a problem. How did you decide what mattered most, and how did you know your choice was working?$prompt$,
        null::text
      )
    ) as seed(
      project_title,
      project_tags,
      project_category,
      short_description,
      impact_description,
      full_description,
      project_managers,
      faculty_advisor,
      faculty_advisor_url,
      prompt_text,
      video_url
    )
  loop
    select p.id
      into seed_project_id
      from public.projects as p
     where p."projectTitle" = project_data.project_title
     order by p.id
     limit 1;

    if seed_project_id is null then
      insert into public.projects (
        "projectTitle",
        tags,
        category,
        "shortDescription",
        "impactDescription",
        "fullDescription",
        "projectManagers",
        "facultyAdvisor",
        "facultyAdvisorUrl",
        published,
        year,
        is_hiring
      ) values (
        project_data.project_title,
        project_data.project_tags,
        project_data.project_category,
        project_data.short_description,
        project_data.impact_description,
        project_data.full_description,
        project_data.project_managers,
        project_data.faculty_advisor,
        project_data.faculty_advisor_url,
        true,
        2026,
        true
      )
      returning id into seed_project_id;
    else
      update public.projects
         set tags = project_data.project_tags,
             category = project_data.project_category,
             "shortDescription" = project_data.short_description,
             "impactDescription" = project_data.impact_description,
             "fullDescription" = project_data.full_description,
             "projectManagers" = project_data.project_managers,
             "facultyAdvisor" = project_data.faculty_advisor,
             "facultyAdvisorUrl" = project_data.faculty_advisor_url,
             published = true,
             year = 2026,
             is_hiring = true
       where id = seed_project_id;
    end if;

    if project_data.prompt_text is not null or project_data.video_url is not null then
      insert into public.hiring_project_prompts (project_id, prompt_text, video_url)
      values (seed_project_id, project_data.prompt_text, project_data.video_url)
      on conflict (project_id) do update
        set prompt_text = excluded.prompt_text,
            video_url = excluded.video_url;
    end if;
  end loop;
end
$$;

comment on column public.projects."projectManagers" is
  'Names of project managers listed in the hiring brief; separate from pmEmail, which identifies the authenticated project owner.';
comment on column public.projects."facultyAdvisor" is
  'Optional faculty advisor listed in the hiring brief.';
comment on column public.projects."facultyAdvisorUrl" is
  'Optional public faculty advisor profile URL from the hiring brief.';

commit;
