const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { randomUUID } = require('node:crypto');
const ts = require('typescript');
const { PGlite } = require('@electric-sql/pglite');

function loadTs(relative, mocks = {}) {
  const filename = path.resolve(relative);
  const output = ts.transpileModule(fs.readFileSync(filename, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true },
  }).outputText;
  const module = { exports: {} };
  const localRequire = (id) => {
    if (Object.hasOwn(mocks, id)) return mocks[id];
    if (id.startsWith('.')) return loadTs(path.resolve(path.dirname(filename), id + '.ts'), mocks);
    return require(id);
  };
  new Function('require', 'module', 'exports', output)(localRequire, module, module.exports);
  return module.exports;
}

test('Next.js rejects privileged keys in the public Supabase variable', () => {
  const source = fs.readFileSync('next.config.js', 'utf8');
  const configure = (key) => {
    const context = vm.createContext({ Buffer, URL, module: { exports: {} },
      process: { env: { NEXT_PUBLIC_SUPABASE_ANON_KEY: key } },
      require: (id) => { assert.equal(id, '@next/mdx'); return () => (config) => config; },
    });
    return vm.runInContext(source, context);
  };
  const jwt = (role) => `header.${Buffer.from(JSON.stringify({ role })).toString('base64url')}.signature`;
  assert.throws(() => configure('sb_secret_test'), /never a Supabase secret/);
  assert.throws(() => configure(jwt('service_role')), /never a Supabase secret/);
  assert.doesNotThrow(() => configure('sb_publishable_test'));
  assert.doesNotThrow(() => configure(jwt('anon')));
});

const sampleApplication = (id = randomUUID()) => ({
  id, submitted_at: new Date().toISOString(), full_name: 'Test Applicant',
  queens_email: `${id}@queensu.ca`, preferred_email: `${id}@example.org`,
  graduation_year: 2028, faculty: 'Engineering', major: 'Computing',
  video_url: 'https://example.org/video', why_qmind: 'A sample application response.',
  skills_experience: 'A sample experience response.', fun_fact: 'A test fact.',
  referral_source: 'Other', social_confirmed: true, consent: true,
  ranked_project_ids: [1, 2, 3], ranked_project_titles: ['One', 'Two', 'Three'],
  resume_storage_path: `${id}/resume.pdf`, spreadsheet_status: 'pending',
});

test('all PR migrations execute and enforce data, RPC, prompt, and storage permissions', async () => {
  const db = new PGlite();
  try {
    // Fixture for the existing site's schema (not created by this PR).
    await db.exec(`
      create role anon; create role authenticated; create role service_role bypassrls;
      grant usage on schema public to anon, authenticated, service_role;
      alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
      create schema storage;
      grant usage on schema storage to anon, authenticated, service_role;
      create table storage.buckets(id text primary key, name text, public boolean, file_size_limit bigint, allowed_mime_types text[]);
      create table storage.objects(id uuid primary key, bucket_id text, name text);
      alter table storage.objects enable row level security;
      grant all on storage.objects to anon, authenticated, service_role;
      create policy old_broad_policy on storage.objects for all to anon, authenticated using (true) with check (true);
      create table public.projects (
        id bigint generated by default as identity primary key,
        "projectTitle" text, tags text[], category text, "githubUrl" text,
        "projectImages" text[], "shortDescription" text, "impactDescription" text,
        "fullDescription" text, "pmEmail" text, published boolean, year integer
      );
      insert into public.projects ("projectTitle", "projectImages", "githubUrl", "pmEmail", published)
        values ('DCP Federated Learning', array['keep-image'], 'keep-repo', 'owner@example.org', false);
    `);
    const migrations = fs.readdirSync('supabase/migrations').filter((name) => name.endsWith('.sql')).sort();
    const legacy = sampleApplication();
    for (const name of migrations) {
      await db.exec(fs.readFileSync(path.join('supabase/migrations', name), 'utf8'));
      if (name === '202608220001_create_applications.sql') {
        await db.query(`insert into public.applications select * from jsonb_populate_record(null::public.applications, $1::jsonb)`,
          [JSON.stringify({ ...legacy, demographic_responses: { genderIdentity: 'Woman' } })]);
        await db.exec('set role anon');
        assert.equal((await db.query('select * from public.applications')).rows.length, 0, 'original RLS denies anonymous reads');
        await db.exec('reset role');
      }
    }
    assert.equal(migrations.length, 7);
    assert.equal((await db.query('select count(*)::int as n from public.projects')).rows[0].n, 10);
    await db.exec(fs.readFileSync('supabase/migrations/202609060004_seed_2026_hiring_projects.sql', 'utf8'));
    assert.equal((await db.query('select count(*)::int as n from public.projects')).rows[0].n, 10, 'seed rerun does not duplicate projects');
    const existing = (await db.query('select "projectImages", "githubUrl", "pmEmail" from public.projects where id = 1')).rows[0];
    assert.deepEqual(existing, { projectImages: ['keep-image'], githubUrl: 'keep-repo', pmEmail: 'owner@example.org' });
    assert.deepEqual((await db.query('select responses from careers_private.application_demographics where application_id = $1', [legacy.id])).rows[0].responses, { genderIdentity: 'Woman' });
    assert.equal((await db.query("select count(*)::int as n from information_schema.columns where table_schema='public' and table_name='applications' and column_name='demographic_responses'")).rows[0].n, 0);
    const bucket = (await db.query("select * from storage.buckets where id='application-resumes'")).rows[0];
    assert.equal(bucket.public, false);
    assert.equal(Number(bucket.file_size_limit), 8388608);
    assert.deepEqual(bucket.allowed_mime_types, ['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
    await db.exec(`
      insert into storage.objects values ('${randomUUID()}', 'application-resumes', 'private.pdf'), ('${randomUUID()}', 'projects', 'public.png');
      update public.projects set published = false where id = 1;
      update public.projects set category = 'Other' where id = 2;
    `);
    for (const role of ['anon', 'authenticated']) {
      await db.exec(`set role ${role}`);
      await assert.rejects(db.query('select * from public.applications'), /permission denied/);
      await assert.rejects(db.query('select * from careers_private.application_demographics'), /permission denied/);
      await assert.rejects(db.query('select * from careers_private.email_verifications'), /permission denied/);
      for (const sql of [
        "select public.save_careers_application('{}', '{}')",
        `select public.request_careers_email_code('test@example.org', '${randomUUID()}', 'hash')`,
        `select public.verify_careers_email_code('${randomUUID()}', 'hash')`,
      ]) await assert.rejects(db.query(sql), /permission denied/);
      const prompts = (await db.query('select project_id from public.hiring_project_prompts')).rows;
      assert.equal(prompts.length, 8);
      assert.ok(prompts.every((row) => ![1, 2].includes(Number(row.project_id))));
      assert.deepEqual((await db.query('select name from storage.objects')).rows, [{ name: 'public.png' }], 'restrictive policy defeats pre-existing broad access');
      await assert.rejects(db.query(`insert into storage.objects values ('${randomUUID()}', 'application-resumes', 'attack.pdf')`), /row-level security/);
      assert.equal((await db.query("delete from storage.objects where bucket_id='application-resumes' returning id")).rows.length, 0);
      await assert.rejects(db.query('delete from public.hiring_project_prompts returning project_id').then((result) => {
        if (result.rows.length === 0) throw new Error('denied by RLS');
      }), /denied/);
      await db.exec('reset role');
    }
    await db.exec('set role service_role');
    assert.equal((await db.query("select * from storage.objects where bucket_id='application-resumes'")).rows.length, 1);
    const application = sampleApplication();
    await db.query('select public.save_careers_application($1::jsonb, $2::jsonb)', [JSON.stringify(application), JSON.stringify({ firstGeneration: 'Yes' })]);
    assert.equal((await db.query('select * from public.applications where id=$1', [application.id])).rows.length, 1);
    const invalid = sampleApplication();
    await assert.rejects(db.query('select public.save_careers_application($1::jsonb, $2::jsonb)', [JSON.stringify(invalid), '[]']), /check constraint/);
    assert.equal((await db.query('select * from public.applications where id=$1', [invalid.id])).rows.length, 0, 'private failure rolls application back');

    const request = (email, id, hash = 'correct') => db.query('select public.request_careers_email_code($1,$2,$3) as ok', [email, id, hash]);
    const verify = (id, hash) => db.query('select public.verify_careers_email_code($1,$2) as email', [id, hash]);
    const id = randomUUID();
    assert.equal((await request('Test@Example.org', id)).rows[0].ok, true);
    assert.equal((await request('test@example.org', randomUUID())).rows[0].ok, false, 'cooldown normalizes email');
    for (let i = 0; i < 5; i++) assert.equal((await verify(id, 'wrong')).rows[0].email, null);
    assert.equal((await verify(id, 'correct')).rows[0].email, null, 'attempt limit persists');
    const successId = randomUUID();
    await request('success@example.org', successId);
    assert.equal((await verify(successId, 'correct')).rows[0].email, 'success@example.org');
    assert.equal((await verify(successId, 'correct')).rows[0].email, null, 'cannot replay a code');
    const expiredId = randomUUID();
    await request('expired@example.org', expiredId);
    await db.query("update careers_private.email_verifications set expires_at=now()-interval '1 minute' where challenge_id=$1", [expiredId]);
    assert.equal((await verify(expiredId, 'correct')).rows[0].email, null);
    for (let i = 1; i <= 5; i++) {
      await db.exec("update careers_private.email_verifications set sent_at=now()-interval '61 seconds' where email='test@example.org'");
      assert.equal((await request('test@example.org', randomUUID())).rows[0].ok, i < 5, 'hourly limit survives code replacement');
    }
    await db.query('delete from public.applications where id=$1', [application.id]);
    assert.equal((await db.query('select * from careers_private.application_demographics where application_id=$1', [application.id])).rows.length, 0);
  } finally {
    await db.close();
  }
});

test('demographics reject unknown keys, formula payloads, and unexpected answers', () => {
  const { demographicSchema } = loadTs('app/careers/validation.ts');
  assert.equal(demographicSchema.safeParse({ genderIdentity: 'Woman', firstGeneration: 'Prefer not to answer' }).success, true);
  for (const input of [{ genderIdentity: '=Applications!E2' }, { '=Applications!E2': 'Yes' }, { firstGeneration: 'malicious' }]) {
    assert.equal(demographicSchema.safeParse(input).success, false);
  }
});

test('verification proofs reject email changes, expiry, tampering, and missing configuration', () => {
  process.env.CAREERS_VERIFICATION_SECRET = 'test-only-secret-with-at-least-32-characters';
  const { createEmailProof, validateEmailProof, hashEmailCode } = loadTs('app/careers/emailProof.ts');
  const proof = createEmailProof(' Person@queensu.ca ', 1000);
  assert.equal(validateEmailProof(proof, 'person@queensu.ca', 2000), true);
  assert.equal(validateEmailProof(proof, 'someone-else@queensu.ca', 2000), false);
  assert.equal(validateEmailProof(proof, 'person@queensu.ca', 3601000), false);
  assert.equal(validateEmailProof(proof + '.extra', 'person@queensu.ca', 2000), false);
  assert.equal(validateEmailProof('forged.' + proof.split('.')[1], 'person@queensu.ca', 2000), false);
  assert.notEqual(hashEmailCode('challenge-a', '12345678'), hashEmailCode('challenge-b', '12345678'));
  delete process.env.CAREERS_VERIFICATION_SECRET;
  assert.equal(validateEmailProof(proof, 'person@queensu.ca', 2000), false);
});

test('unverified submissions are rejected before any database or storage access', async () => {
  let calls = 0;
  const { submitApplication } = loadTs('app/careers/actions.ts', {
    'next/headers': { cookies: () => ({ get: () => undefined }) },
    '@/utils/supabase/admin': { createAdminClient: () => { calls++; throw new Error('must not be called'); } },
  });
  const form = new FormData();
  form.set('resume', new File(['%PDF-test'], 'resume.pdf', { type: 'application/pdf' }));
  form.set('application', JSON.stringify({
    fullName: 'Test Applicant', queensEmail: 'test@queensu.ca', preferredEmail: 'victim@example.org',
    graduationYear: '2028', faculty: 'Engineering', major: 'Computing', videoUrl: 'https://example.org/video',
    whyQmind: 'This is a sample application response.', skillsExperience: 'This is a sample experience response.',
    funFact: 'A test fact', referralSource: 'Other', socialConfirmed: true, consent: true,
    demographicResponses: {}, rankedProjectIds: [1,2,3], rankedProjectTitles: ['One','Two','Three'],
  }));
  const result = await submitApplication(form);
  assert.equal(result.ok, false);
  assert.match(result.message, /Verify both email/);
  assert.equal(calls, 0);
});

test('reviewer export omits demographics and private storage paths', async () => {
  const originalFetch = global.fetch;
  process.env.GOOGLE_SHEETS_WEBHOOK_URL = 'https://example.org/test';
  process.env.GOOGLE_SHEETS_WEBHOOK_SECRET = 'test';
  let sent;
  global.fetch = async (_url, options) => { sent = JSON.parse(options.body); return { ok: true, json: async () => ({ ok: true }) }; };
  try {
    const { exportApplicationToSpreadsheet } = loadTs('app/careers/spreadsheet.ts');
    await exportApplicationToSpreadsheet({ applicationId: 'test', demographicResponses: { disabilityOrNeurodivergence: 'Yes' }, resumeStoragePath: 'private/path', resumeUrl: 'https://example.org/resume' });
    assert.equal(Object.hasOwn(sent.application, 'demographicResponses'), false);
    assert.equal(Object.hasOwn(sent.application, 'resumeStoragePath'), false);
  } finally {
    global.fetch = originalFetch;
    delete process.env.GOOGLE_SHEETS_WEBHOOK_URL;
    delete process.env.GOOGLE_SHEETS_WEBHOOK_SECRET;
  }
});

test('email code actions use browser-bound challenges and set HTTP-only signed proofs', async () => {
  const originalFetch = global.fetch;
  const previous = Object.fromEntries(['RESEND_API_KEY', 'CAREERS_EMAIL_FROM', 'CAREERS_VERIFICATION_SECRET'].map((key) => [key, process.env[key]]));
  Object.assign(process.env, { RESEND_API_KEY: 'test', CAREERS_EMAIL_FROM: 'test@example.org', CAREERS_VERIFICATION_SECRET: 'test-only-secret-with-at-least-32-characters' });
  const jar = new Map();
  const options = new Map();
  const rpcCalls = [];
  let allowed = true;
  let sent;
  global.fetch = async (_url, request) => { sent = JSON.parse(request.body); return { ok: true }; };
  const { requestEmailCode, verifyEmailCode } = loadTs('app/careers/verificationActions.ts', {
    'next/headers': { cookies: () => ({ get: (key) => jar.has(key) ? { value: jar.get(key) } : undefined, set: (key, value, opts) => { jar.set(key, value); options.set(key, opts); } }) },
    '@/utils/supabase/admin': { createAdminClient: () => ({ rpc: async (name, args) => {
      rpcCalls.push({ name, args });
      return { error: null, data: name === 'request_careers_email_code' ? allowed : 'test@queensu.ca' };
    } }) },
  });
  try {
    assert.equal((await requestEmailCode('test@example.org', 'queens')).ok, false);
    assert.equal((await verifyEmailCode('12345678', 'queens')).ok, false, 'no exchange without browser challenge');
    assert.equal(rpcCalls.length, 0);
    assert.equal((await requestEmailCode('TEST@queensu.ca', 'queens')).ok, true);
    assert.deepEqual(sent.to, ['test@queensu.ca']);
    const code = sent.text.match(/code is (\d{8})/)[1];
    assert.notEqual(rpcCalls[0].args.p_code_hash, code);
    assert.equal(rpcCalls[0].args.p_code_hash.length, 64);
    assert.equal(options.get('careers-challenge-queens').httpOnly, true);
    assert.equal((await verifyEmailCode(code, 'queens')).ok, true);
    assert.equal(rpcCalls[1].args.p_challenge_id, rpcCalls[0].args.p_challenge_id);
    assert.equal(rpcCalls[1].args.p_code_hash, rpcCalls[0].args.p_code_hash);
    const proof = jar.get('careers-verified-queens');
    const { validateEmailProof } = loadTs('app/careers/emailProof.ts');
    assert.equal(validateEmailProof(proof, 'test@queensu.ca'), true);
    assert.equal(options.get('careers-verified-queens').httpOnly, true);
    assert.equal(options.get('careers-verified-queens').sameSite, 'strict');
    allowed = false;
    sent = undefined;
    assert.equal((await requestEmailCode('test@queensu.ca', 'queens')).ok, false);
    assert.equal(sent, undefined, 'rate-limited requests do not send mail');
  } finally {
    global.fetch = originalFetch;
    for (const [key, value] of Object.entries(previous)) {
      if (value === undefined) delete process.env[key]; else process.env[key] = value;
    }
  }
});

test('verified submissions use canonical project titles and atomically save private demographics', async () => {
  process.env.CAREERS_VERIFICATION_SECRET = 'test-only-secret-with-at-least-32-characters';
  const { createEmailProof } = loadTs('app/careers/emailProof.ts');
  const proofs = { 'careers-verified-queens': createEmailProof('test@queensu.ca'), 'careers-verified-preferred': createEmailProof('test@example.org') };
  const writes = [];
  const projects = [1,2,3].map((id) => ({ id, projectTitle: `Canonical ${id}` }));
  const query = { select() { return this; }, in() { return this; }, eq: async () => ({ data: projects }) };
  const admin = {
    from: () => ({ ...query, update: () => ({ eq: async () => ({ error: null }) }) }),
    storage: { from: () => ({ upload: async () => { writes.push('upload'); return { error: null }; }, remove: async () => ({ error: null }) }) },
    rpc: async (_name, args) => { writes.push(args); return { error: null }; },
  };
  const { submitApplication } = loadTs('app/careers/actions.ts', {
    'next/headers': { cookies: () => ({ get: (key) => proofs[key] ? { value: proofs[key] } : undefined }) },
    '@/utils/supabase/admin': { createAdminClient: () => admin },
  });
  const payload = {
    fullName: 'Test Applicant', queensEmail: 'test@queensu.ca', preferredEmail: 'test@example.org',
    graduationYear: '2028', faculty: 'Engineering', major: 'Computing', videoUrl: 'https://example.org/video',
    whyQmind: 'This is a sample application response.', skillsExperience: 'This is a sample experience response.',
    funFact: 'A test fact', referralSource: 'Other', socialConfirmed: true, consent: true,
    demographicResponses: { firstGeneration: 'Yes' }, rankedProjectIds: [3,1,2], rankedProjectTitles: ['=attack','forged','fake'],
  };
  const form = new FormData();
  form.set('resume', new File(['%PDF-test'], 'resume.pdf', { type: 'application/pdf' }));
  form.set('application', JSON.stringify(payload));
  try {
    assert.equal((await submitApplication(form)).ok, true);
    assert.deepEqual(writes[1].p_application.ranked_project_titles, ['Canonical 3','Canonical 1','Canonical 2']);
    assert.equal(Object.hasOwn(writes[1].p_application, 'demographic_responses'), false);
    assert.deepEqual(writes[1].p_demographics, { firstGeneration: 'Yes' });
    writes.length = 0;
    form.set('application', JSON.stringify({ ...payload, preferredEmail: 'victim@example.org' }));
    assert.equal((await submitApplication(form)).ok, false);
    assert.equal(writes.length, 0, 'changing a verified email requires another proof');
    form.set('application', JSON.stringify({ ...payload, preferredEmail: 'test@queensu.ca' }));
    delete proofs['careers-verified-preferred'];
    assert.equal((await submitApplication(form)).ok, true, 'same address needs only one proof');
  } finally {
    delete process.env.CAREERS_VERIFICATION_SECRET;
  }
});

test('spreadsheet rebuilds escape formulas and cleanup removes old demographic cells', () => {
  const context = vm.createContext({});
  vm.runInContext(fs.readFileSync('docs/google-sheets-webhook.gs', 'utf8'), context);
  const injections = ['=Applications!E2', '+1', '-1', '@SUM(A1)', '\t=Applications!E2'];
  for (const value of injections) assert.equal(context.safeCell(value), "'" + value);
  assert.equal(context.safeCell(42), 42);
  const writes = [];
  const clears = [];
  const range = { setValues(rows) { writes.push(...rows); }, clearContent() { clears.push('raw demographics'); }, setValue() {} };
  const target = { clear() { clears.push('summary'); }, appendRow() {}, getRange: () => range, setColumnWidth() {}, setColumnWidths() {} };
  context.getApplicationsSheet = () => ({ getLastRow: () => 2, getRange: () => ({ ...range, getValues: () => [injections.slice(0, 3)] }) });
  context.getOrCreateSheet = () => target;
  context.styleHeader = () => {};
  context.refreshProjectDemand();
  assert.equal(writes.length, 3);
  assert.ok(writes.every((row) => row[0].startsWith("'")));
  writes.length = 0;
  const row = Array(25).fill(''); row[0] = 'id'; row[2] = '=Applications!E2';
  context.getApplicationsSheet = () => ({ getLastRow: () => 2, getRange: () => ({ ...range, getValues: () => [row] }) });
  target.getLastRow = () => 0;
  context.formatReviewQueue = () => {};
  context.rebuildReviewQueue();
  assert.equal(writes[0][2], "'=Applications!E2");
  context.getSpreadsheet = () => ({ getSheetByName: () => target });
  context.removeLegacyDemographics();
  assert.ok(clears.includes('raw demographics'));
  assert.ok(clears.includes('summary'));
  assert.doesNotMatch(fs.readFileSync('docs/google-sheets-webhook.gs', 'utf8'), /\["Demographics", "W"\]/);
});
