const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { randomUUID } = require('node:crypto');
const ts = require('typescript');
const { PGlite } = require('@electric-sql/pglite');

function loadTs(relative, mocks = {}) {
  const filename = path.resolve(relative);
  const output = ts.transpileModule(fs.readFileSync(filename, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true },
  }).outputText;
  const module = { exports: {} };
  const localRequire = (id) => {
    if (Object.hasOwn(mocks, id)) return mocks[id];
    if (id.startsWith('.')) return loadTs(path.resolve(path.dirname(filename), id + '.ts'), mocks);
    return require(id);
  };
  new Function('require', 'module', 'exports', output)(localRequire, module, module.exports);
  return module.exports;
}

test('Next.js rejects privileged keys in the public Supabase variable', () => {
  const source = fs.readFileSync('next.config.js', 'utf8');
  const configure = (key) => {
    const context = vm.createContext({ Buffer, URL, module: { exports: {} },
      process: { env: { NEXT_PUBLIC_SUPABASE_ANON_KEY: key } },
      require: (id) => { assert.equal(id, '@next/mdx'); return () => (config) => config; },
    });
    return vm.runInContext(source, context);
  };
  const jwt = (role) => `header.${Buffer.from(JSON.stringify({ role })).toString('base64url')}.signature`;
  assert.throws(() => configure('sb_secret_test'), /never a Supabase secret/);
  assert.throws(() => configure(jwt('service_role')), /never a Supabase secret/);
  assert.doesNotThrow(() => configure('sb_publishable_test'));
  assert.doesNotThrow(() => configure(jwt('anon')));
});

const sampleApplication = (id = randomUUID()) => ({
  id, submitted_at: new Date().toISOString(), full_name: 'Test Applicant',
  queens_email: `${id}@queensu.ca`, preferred_email: `${id}@example.org`,
  graduation_year: 2028, faculty: 'Engineering', major: 'Computing',
  video_url: 'https://example.org/video', why_qmind: 'A sample application response.',
  skills_experience: 'A sample experience response.', fun_fact: 'A test fact.',
  referral_source: 'Other', social_confirmed: true, consent: true,
  ranked_project_ids: [1, 2, 3], ranked_project_titles: ['One', 'Two', 'Three'],
  resume_storage_path: `${id}/resume.pdf`, spreadsheet_status: 'pending',
});

test('all PR migrations execute and enforce data, RPC, prompt, and storage permissions', async () => {
  const db = new PGlite();
  try {
    // Fixture for the existing site's schema (not created by this PR).
    await db.exec(`
      create role anon; create role authenticated; create role service_role bypassrls;
      grant usage on schema public to anon, authenticated, service_role;
      alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
      create schema storage;
      grant usage on schema storage to anon, authenticated, service_role;
      create table storage.buckets(id text primary key, name text, public boolean, file_size_limit bigint, allowed_mime_types text[]);
      create table storage.objects(id uuid primary key, bucket_id text, name text);
      alter table storage.objects enable row level security;
      grant all on storage.objects to anon, authenticated, service_role;
      create policy old_broad_policy on storage.objects for all to anon, authenticated using (true) with check (true);
      create table public.projects (
        id bigint generated by default as identity primary key,
        "projectTitle" text, tags text[], category text, "githubUrl" text,
        "projectImages" text[], "shortDescription" text, "impactDescription" text,
        "fullDescription" text, "pmEmail" text, published boolean, year integer
      );
      insert into public.projects ("projectTitle", "projectImages", "githubUrl", "pmEmail", published)
        values ('DCP Federated Learning', array['keep-image'], 'keep-repo', 'owner@example.org', false);
    `);
    const migrationDirectory = 'supabase/migrations/careers';
    const migrations = fs.readdirSync(migrationDirectory).filter((name) => name.endsWith('.sql')).sort();
    const legacy = sampleApplication();
    for (const name of migrations) {
      await db.exec(fs.readFileSync(path.join(migrationDirectory, name), 'utf8'));
      if (name === '202608220001_create_applications.sql') {
        await db.query(`insert into public.applications select * from jsonb_populate_record(null::public.applications, $1::jsonb)`,
          [JSON.stringify({ ...legacy, demographic_responses: { genderIdentity: 'Woman' } })]);
        await db.exec('set role anon');
        assert.equal((await db.query('select * from public.applications')).rows.length, 0, 'original RLS denies anonymous reads');
        await db.exec('reset role');
      }
    }
    assert.equal(migrations.length, 11);
    assert.equal((await db.query('select count(*)::int as n from public.projects')).rows[0].n, 15);
    await db.exec(fs.readFileSync(path.join(migrationDirectory, '202609060004_seed_2026_hiring_projects.sql'), 'utf8'));
    assert.equal((await db.query('select count(*)::int as n from public.projects')).rows[0].n, 15, 'seed rerun does not duplicate projects');
    await db.exec(fs.readFileSync(path.join(migrationDirectory, '202609070002_seed_additional_hiring_projects.sql'), 'utf8'));
    assert.equal((await db.query('select count(*)::int as n from public.projects')).rows[0].n, 15, 'additional seed rerun does not duplicate projects');
    await db.exec(fs.readFileSync(path.join(migrationDirectory, '202609080001_seed_final_hiring_projects.sql'), 'utf8'));
    assert.equal((await db.query('select count(*)::int as n from public.projects')).rows[0].n, 15, 'final seed rerun does not duplicate projects');
    await db.exec(fs.readFileSync(path.join(migrationDirectory, '202609080002_update_wildfire_and_diffusion_projects.sql'), 'utf8'));
    assert.equal((await db.query('select count(*)::int as n from public.projects')).rows[0].n, 15, 'project update rerun does not duplicate projects');
    const existing = (await db.query('select "projectImages", "githubUrl", "pmEmail" from public.projects where id = 1')).rows[0];
    assert.deepEqual(existing, { projectImages: ['keep-image'], githubUrl: 'keep-repo', pmEmail: 'owner@example.org' });
    const wildfire = (await db.query('select "fullDescription", "projectManagers" from public.projects where "projectTitle" = $1', ['Wildfire Discovery Drone'])).rows[0];
    assert.match(wildfire.fullDescription, /FLIR A700-series thermal camera/);
    assert.deepEqual(wildfire.projectManagers, ['Viona Hashemkhani']);
    const diffusion = (await db.query('select "fullDescription", "facultyAdvisor" from public.projects where "projectTitle" = $1', ['Diffusion-Model Rendering for Re-Themable Games'])).rows[0];
    assert.match(diffusion.fullDescription, /densely factored dataset/);
    assert.equal(diffusion.facultyAdvisor, 'Robert Ciborowsko');
    const prompts = (await db.query(`
      select p."projectTitle", h.prompt_text
      from public.projects p
      join public.hiring_project_prompts h on h.project_id = p.id
      where p."projectTitle" in ('Wildfire Discovery Drone', 'Diffusion-Model Rendering for Re-Themable Games')
      order by p."projectTitle"
    `)).rows;
    assert.deepEqual(prompts, [
      { projectTitle: 'Diffusion-Model Rendering for Re-Themable Games', prompt_text: 'Tell me what your passion for AI comes from. What are your goals and why do you pursue them?' },
      { projectTitle: 'Wildfire Discovery Drone', prompt_text: 'Tell me an interesting story about yourself.' },
    ]);
    assert.deepEqual((await db.query('select responses from careers_private.application_demographics where application_id = $1', [legacy.id])).rows[0].responses, { genderIdentity: 'Woman' });
    assert.equal((await db.query("select count(*)::int as n from information_schema.columns where table_schema='public' and table_name='applications' and column_name='demographic_responses'")).rows[0].n, 0);
    const bucket = (await db.query("select * from storage.buckets where id='application-resumes'")).rows[0];
    assert.equal(bucket.public, false);
    assert.equal(Number(bucket.file_size_limit), 8388608);
    assert.deepEqual(bucket.allowed_mime_types, ['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
    await db.exec(`
      insert into storage.objects values ('${randomUUID()}', 'application-resumes', 'private.pdf'), ('${randomUUID()}', 'projects', 'public.png');
      update public.projects set published = false where id = 1;
      update public.projects set category = 'Other' where id = 2;
    `);
    for (const role of ['anon', 'authenticated']) {
      await db.exec(`set role ${role}`);
      await assert.rejects(db.query('select * from public.applications'), /permission denied/);
      await assert.rejects(db.query('select * from careers_private.application_demographics'), /permission denied/);
      for (const sql of [
        "select public.save_careers_application('{}', '{}')",
      ]) await assert.rejects(db.query(sql), /permission denied/);
      const prompts = (await db.query('select project_id from public.hiring_project_prompts')).rows;
      assert.equal(prompts.length, 13);
      assert.ok(prompts.every((row) => ![1, 2].includes(Number(row.project_id))));
      assert.deepEqual((await db.query('select name from storage.objects')).rows, [{ name: 'public.png' }], 'restrictive policy defeats pre-existing broad access');
      await assert.rejects(db.query(`insert into storage.objects values ('${randomUUID()}', 'application-resumes', 'attack.pdf')`), /row-level security/);
      assert.equal((await db.query("delete from storage.objects where bucket_id='application-resumes' returning id")).rows.length, 0);
      await assert.rejects(db.query('delete from public.hiring_project_prompts returning project_id').then((result) => {
        if (result.rows.length === 0) throw new Error('denied by RLS');
      }), /denied/);
      await db.exec('reset role');
    }
    await db.exec('set role service_role');
    assert.equal((await db.query("select * from storage.objects where bucket_id='application-resumes'")).rows.length, 1);
    const application = sampleApplication();
    await db.query('select public.save_careers_application($1::jsonb, $2::jsonb)', [JSON.stringify(application), JSON.stringify({ firstGeneration: 'Yes' })]);
    assert.equal((await db.query('select * from public.applications where id=$1', [application.id])).rows.length, 1);
    const invalid = sampleApplication();
    await assert.rejects(db.query('select public.save_careers_application($1::jsonb, $2::jsonb)', [JSON.stringify(invalid), '[]']), /check constraint/);
    assert.equal((await db.query('select * from public.applications where id=$1', [invalid.id])).rows.length, 0, 'private failure rolls application back');

    await db.query('delete from public.applications where id=$1', [application.id]);
    assert.equal((await db.query('select * from careers_private.application_demographics where application_id=$1', [application.id])).rows.length, 0);
  } finally {
    await db.close();
  }
});

test('demographics reject unknown keys, formula payloads, and unexpected answers', () => {
  const { demographicSchema } = loadTs('app/careers/validation.ts');
  assert.equal(demographicSchema.safeParse({ genderIdentity: 'Woman', firstGeneration: 'Prefer not to answer' }).success, true);
  for (const input of [{ genderIdentity: '=Applications!E2' }, { '=Applications!E2': 'Yes' }, { firstGeneration: 'malicious' }]) {
    assert.equal(demographicSchema.safeParse(input).success, false);
  }
});

test('reviewer export includes demographics and omits private storage paths', async () => {
  const originalFetch = global.fetch;
  process.env.GOOGLE_SHEETS_WEBHOOK_URL = 'https://example.org/test';
  process.env.GOOGLE_SHEETS_WEBHOOK_SECRET = 'test';
  let sent;
  global.fetch = async (_url, options) => { sent = JSON.parse(options.body); return { ok: true, json: async () => ({ ok: true }) }; };
  try {
    const { exportApplicationToSpreadsheet } = loadTs('app/careers/spreadsheet.ts');
    await exportApplicationToSpreadsheet({ applicationId: 'test', demographicResponses: { disabilityOrNeurodivergence: 'Yes' }, resumeStoragePath: 'private/path', resumeUrl: 'https://example.org/resume' });
    assert.deepEqual(sent.application.demographicResponses, { disabilityOrNeurodivergence: 'Yes' });
    assert.equal(Object.hasOwn(sent.application, 'resumeStoragePath'), false);
  } finally {
    global.fetch = originalFetch;
    delete process.env.GOOGLE_SHEETS_WEBHOOK_URL;
    delete process.env.GOOGLE_SHEETS_WEBHOOK_SECRET;
  }
});

test('public submissions use canonical project titles and atomically save private demographics', async () => {
  const originalFetch = global.fetch;
  const originalWebhookUrl = process.env.GOOGLE_SHEETS_WEBHOOK_URL;
  const originalWebhookSecret = process.env.GOOGLE_SHEETS_WEBHOOK_SECRET;
  const originalSiteUrl = process.env.NEXT_PUBLIC_SITE_URL;
  const writes = [];
  let spreadsheetApplication;
  let spreadsheetAttempts = 0;
  process.env.GOOGLE_SHEETS_WEBHOOK_URL = 'https://example.org/test';
  process.env.GOOGLE_SHEETS_WEBHOOK_SECRET = 'test';
  process.env.NEXT_PUBLIC_SITE_URL = 'https://www.qmind.ca';
  global.fetch = async (_url, options) => {
    spreadsheetAttempts += 1;
    if (spreadsheetAttempts === 1) throw new Error('temporary webhook failure');
    spreadsheetApplication = JSON.parse(options.body).application;
    return { ok: true, json: async () => ({ ok: true }) };
  };
  const projects = [1,2,3].map((id) => ({ id, projectTitle: `Canonical ${id}` }));
  const query = {
    select() { return this; },
    in() { return this; },
    eq(field) { return field === 'is_hiring' ? Promise.resolve({ data: projects }) : this; },
  };
  const admin = {
    from: () => ({ ...query, update: () => ({ eq: async () => ({ error: null }) }) }),
    storage: { from: () => ({ upload: async () => { writes.push('upload'); return { error: null }; }, remove: async () => ({ error: null }) }) },
    rpc: async (_name, args) => { writes.push(args); return { error: null }; },
  };
  try {
    const { submitApplication } = loadTs('app/careers/actions.ts', {
      '@/utils/supabase/admin': { createAdminClient: () => admin },
    });
    const payload = {
      fullName: 'Test Applicant', queensEmail: 'test@queensu.ca', preferredEmail: 'test@example.org',
      graduationYear: '2028', faculty: 'Engineering', major: 'Computing', videoUrl: 'https://example.org/video',
      whyQmind: 'This is a sample application response.', skillsExperience: 'This is a sample experience response.',
      funFact: 'A test fact', referralSource: 'Other', referralOther: 'Test', socialConfirmed: true, consent: true,
      demographicResponses: { firstGeneration: 'Yes' }, rankedProjectIds: [3,1,2], rankedProjectTitles: ['=attack','forged','fake'],
    };
    const form = new FormData();
    form.set('resume', new File(['%PDF-test'], 'resume.pdf', { type: 'application/pdf' }));
    form.set('application', JSON.stringify(payload));
    const result = await submitApplication(form);
    assert.equal(result.ok, true);
    assert.equal(result.spreadsheetStatus, 'synced', 'a transient spreadsheet failure should be retried');
    assert.equal(spreadsheetAttempts, 2);
    assert.equal(spreadsheetApplication.resumeUrl.startsWith('https://www.qmind.ca/careers/resumes/'), true);
    assert.deepEqual(writes[1].p_application.ranked_project_titles, ['Canonical 3','Canonical 1','Canonical 2']);
    assert.equal(Object.hasOwn(writes[1].p_application, 'demographic_responses'), false);
    assert.deepEqual(writes[1].p_demographics, { firstGeneration: 'Yes' });
  } finally {
    global.fetch = originalFetch;
    if (originalWebhookUrl === undefined) delete process.env.GOOGLE_SHEETS_WEBHOOK_URL;
    else process.env.GOOGLE_SHEETS_WEBHOOK_URL = originalWebhookUrl;
    if (originalWebhookSecret === undefined) delete process.env.GOOGLE_SHEETS_WEBHOOK_SECRET;
    else process.env.GOOGLE_SHEETS_WEBHOOK_SECRET = originalWebhookSecret;
    if (originalSiteUrl === undefined) delete process.env.NEXT_PUBLIC_SITE_URL;
    else process.env.NEXT_PUBLIC_SITE_URL = originalSiteUrl;
  }
});

test('spreadsheet rebuilds escape formulas and restores demographic export cells', () => {
  const context = vm.createContext({});
  vm.runInContext(fs.readFileSync('docs/google-sheets-webhook.gs', 'utf8'), context);
  const injections = ['=Applications!E2', '+1', '-1', '@SUM(A1)', '\t=Applications!E2'];
  for (const value of injections) assert.equal(context.safeCell(value), "'" + value);
  assert.equal(context.safeCell(42), 42);
  const writes = [];
  const clears = [];
  const range = { setValues(rows) { writes.push(...rows); }, clearContent() { clears.push('raw demographics'); }, setValue() {} };
  const target = { clear() { clears.push('summary'); }, appendRow() {}, getRange: () => range, setColumnWidth() {}, setColumnWidths() {} };
  context.getApplicationsSheet = () => ({ getLastRow: () => 2, getRange: () => ({ ...range, getValues: () => [injections.slice(0, 3)] }) });
  context.getOrCreateSheet = () => target;
  context.styleHeader = () => {};
  context.refreshProjectDemand();
  assert.equal(writes.length, 3);
  assert.ok(writes.every((row) => row[0].startsWith("'")));
  writes.length = 0;
  const row = Array(25).fill(''); row[0] = 'id'; row[2] = '=Applications!E2';
  context.getApplicationsSheet = () => ({ getLastRow: () => 2, getRange: () => ({ ...range, getValues: () => [row] }) });
  target.getLastRow = () => 0;
  context.formatReviewQueue = () => {};
  context.rebuildReviewQueue();
  assert.equal(writes[0][2], "'=Applications!E2");
  context.getSpreadsheet = () => ({ getSheetByName: () => target });
  context.refreshDemographicSummary();
  assert.ok(clears.includes('summary'));
  assert.match(fs.readFileSync('docs/google-sheets-webhook.gs', 'utf8'), /safeCell\(JSON\.stringify\(application\.demographicResponses \|\| \{\}\)\)/);
  assert.match(fs.readFileSync('docs/google-sheets-webhook.gs', 'utf8'), /"Demographic responses"/);
});

test('webhook keeps a raw application sync successful when reviewer maintenance fails', () => {
  const logs = [];
  const context = vm.createContext({
    console: { error: (...args) => logs.push(args.join(' ')) },
    JSON,
  });
  vm.runInContext(fs.readFileSync('docs/google-sheets-webhook.gs', 'utf8'), context);

  const rows = [];
  let headerWrites = 0;
  const sheet = {
    getLastRow: () => rows.length ? rows.length + 1 : 1,
    getRange(reference) {
      if (reference === 'A:A') {
        return {
          createTextFinder: () => ({ matchEntireCell: () => ({ findNext: () => null }) }),
        };
      }
      if (reference === 1) {
        headerWrites += 1;
        throw new Error('unexpected header write');
      }
      throw new Error(`unexpected range ${String(reference)}`);
    },
    appendRow: (row) => rows.push(row),
  };

  context.LockService = {
    getScriptLock: () => ({ waitLock() {}, hasLock: () => true, releaseLock() {} }),
  };
  context.PropertiesService = {
    getScriptProperties: () => ({
      getProperty: (key) => ({ WEBHOOK_SECRET: 'test', SPREADSHEET_ID: 'sheet' }[key]),
    }),
  };
  context.ContentService = {
    MimeType: { JSON: 'application/json' },
    createTextOutput: (text) => ({ text, setMimeType() { return this; } }),
  };
  context.getSpreadsheet = () => ({ getSheetByName: (name) => name === 'Applications' ? sheet : null });
  context.setResumeLink = () => { throw new Error('protected resume link range'); };
  context.appendReviewQueueRow = () => {};
  context.refreshProjectDemand = () => {};
  context.refreshDemographicSummary = () => {};

  const response = context.doPost({
    postData: {
      contents: JSON.stringify({
        webhookSecret: 'test',
        application: {
          applicationId: 'application-id', submittedAt: '2026-09-09T00:00:00.000Z',
          fullName: 'Test Applicant', queensEmail: 'test@queensu.ca', preferredEmail: 'test@example.org',
          graduationYear: '2028', faculty: 'Engineering', major: 'Computing',
          rankedProjectTitles: ['One', 'Two', 'Three'], demographicResponses: {},
          socialConfirmed: true, consent: true, resumeUrl: 'https://www.qmind.ca/careers/resumes/application-id',
        },
      }),
    },
  });

  assert.deepEqual(JSON.parse(response.text), { ok: true });
  assert.equal(rows.length, 1);
  assert.equal(headerWrites, 0);
  assert.match(logs.join('\n'), /resume link/);
});
