-- Update the canonical project descriptions to match the hiring brief.
-- Projects are matched by title so their existing ids, images, and ownership
-- data are preserved. Re-running this migration is safe.

update public.projects as p
   set "fullDescription" = case p."projectTitle"
    when 'DCP Federated Learning' then $dcp$In partnership with Distributive, a Kingston-based distributed computing development company, we are building a proof-of-concept package that lets people run federated learning on top of DCP (Distributive's compute-sharing platform). This package will enable multiple hospitals to train one shared Machine Learning model together, without ever having to share their private data with each other, or with us. Initial application focus is predicting treatment response to biologics for psoriatic arthritis. This project will give you hands-on experience researching ML models and implementing federated learning techniques. The package we produce will be made publicly available once it's completed, contributing to the open-source ML ecosystem. We'll likely be building this in JavaScript/TypeScript, so experience with either will come in handy!$dcp$
    when 'Conversational Intelligence for Advanced Process Control' then $process_control$Built in collaboration with Woodgrove Technologies, a mining and mineral processing company based in Toronto, this project explores a conversational AI framework for Advanced Process Control systems used in mineral processing. The framework will bring together process data, controller information, and operational knowledge to help explain complex plant behaviour and controller actions.

These systems automate complex decisions across processes such as grinding, flotation, and separation, but often provide limited visibility into why certain actions are taken. The goal is to use AI to turn this complex and fragmented information into clear, evidence-based natural language explanations, helping engineers and operators better understand system behaviour and make more informed decisions.$process_control$
    when 'TrustLayer' then $trustlayer$This project will develop a responsible AI evaluation system designed to assess AI-generated outputs or actions before they are used in real-world workflows. As organizations increasingly rely on LLMs and AI agents, unreliable, biased, unsafe, or unsupported outputs can become difficult to catch before they affect users or downstream decisions. The project's initial direction is to build a flexible evaluation and quality-assurance layer that can assess factors such as factual reliability, fairness, safety, and whether human review is required. The team will also work with industry partners early in the project to identify a real responsible AI challenge and refine the final system around the needs of the selected client.$trustlayer$
    when 'AI Agent Integration' then $agent_integration$Due to the confidential nature of the client, this description is abridged.

Working with Electric Mind, a consulting firm in downtown Toronto, to develop a governed AI platform that enables intelligent agents to support complex business work. The project focuses on building a reliable and scalable foundation for AI, with agents designed to analyze complex business problems, coordinate information across different areas of an organization, and support informed decision-making and strategic recommendations. The team will focus on building a reliable and scalable foundation for AI, working with the Electric Mind team to integrate AI tools in high impact fields, ensuring accuracy, traceability, and security.$agent_integration$
    when 'ScamBench AI Recruitment Phishing' then $scambench$Generative AI has fueled a massive spike in remote job scams, yet current security tools fail to address how human judgment breaks down during multi-step deceptions. It remains unclear if early trust in a synthetic recruiter profile causes victims to drop their guard, or if a deepfake's visual quality matters more than the mere presence of professional branding. In collaboration with Menlo Park Intelligence, a research organization led by Fred Heiding, Research Fellow at UC Berkeley, this project uses a remote, two-stage recruitment experiment with varying AI visual fidelity. By tracking compliance and hidden metrics like hesitation, we will isolate whether early trust reduces later scrutiny, providing the foundational data needed to design better cybersecurity defenses.$scambench$
    when 'Beyond AUROC: Clinical Readiness of ED Chest-Pain AI' then $beyond_auroc$Can an AI model look excellent on paper and still be unready for the bedside? This project asks what evidence is needed before a chest-pain model can be trusted in real emergency-department decisions.

Emergency clinicians must identify acute coronary syndrome quickly while avoiding unnecessary admission, prolonged observation, and testing for lower-risk patients. AI and Machine-learning models may help, but a high area under the receiver operating characteristic curve (AUROC) only shows discrimination. It does not establish that predicted risks are accurate, thresholds are safe, results generalize, or the model fits the clinical workflow.

Beyond AUROC will update the evidence on AI/ML models used for diagnosis, short-term coronary prognosis, and coronary-risk-informed disposition in adults presenting to the ED with chest pain or suspected ACS. The review will evaluate clinical readiness using current prediction-model guidance. Its findings will then shape a feasible, workflow-constrained benchmark using MIMIC-IV data, subject to access and linkage feasibility.$beyond_auroc$
    when 'LLM-Enhanced Decision Making Agents for Cloud Autoscaling' then $cloud_autoscaling$This project explores the use of large language models as intelligent decision-making agents for dynamic cloud resource management. We will develop an LLM-enhanced autoscaling controller that interprets real-time system telemetry such as CPU utilization, request traffic, response latency, and resource availability to determine when and how cloud resources should be scaled.

By integrating contextual information and operational objectives alongside traditional system metrics, the controller aims to make more informed and adaptable scaling decisions. Traditional cloud autoscaling methods typically rely on predefined thresholds or control policies that react to changes in system utilization. While effective, these approaches have limited ability to incorporate higher-level context or adapt their decision-making strategy to unfamiliar conditions. Our research will examine under what conditions LLM-based reasoning provides meaningful value, while evaluating trade-offs in system performance, resource efficiency and adaptability.$cloud_autoscaling$
    when 'Uncertainty-Aware Deep Learning for Parkinsonian Motor Symptom Severity Estimation from Monocular Video' then $parkinsonian$Rather than producing a binary prediction of whether a patient has Parkinson’s disease, this project explores computer vision for uncertainty-aware assessment of Parkinson’s motor symptoms from monocular video. Using pose estimation and temporal deep learning, the model would quantify movement patterns and estimate motor symptom severity while communicating how uncertain it is in its predictions, such as through confidence or prediction intervals. The project will also examine the ethical implications of using AI for neurological assessment, including whether model performance and uncertainty differ across patient populations, how potential biases in training data may affect predictions, and when an AI system should defer to clinician judgement rather than provide an assessment. By integrating uncertainty, explainability, fairness, and human oversight into model evaluation, the project aims to explore how computer vision systems can provide more transparent, reliable, and ethically responsible support for clinical decision-making.$parkinsonian$
    when 'CanopyMap' then $canopymap$Two of the biggest pain points for agricultural tech and a barrier to automation is measuring plant growth and obtaining quality training data at a large scale. Farming environments can vary a lot and the hardware that is used to monitor them can often be in very different conditions which makes adapting a single model to different environments very challenging.

Lots of research papers cover outdoor farming, very few try to fix the gap in training data for indoor environments. That's what we're trying to fix with CanopyMap. We have access to an aeroponic farm with lots of cameras. We are going to use existing models to run image segmentation on the plants and using that try to measure the plant growth over time. This will eventually help the farm automate its growth optimization algorithm.$canopymap$
    when 'Mechanistic Interpretability of Test-Time Reasoning in Large Language Models' then $mechanistic$Ever wondered what's actually happening inside a reasoning model when it "thinks"?

Modern reasoning models like GPT-5, Gemini 3, and Deepseek-R1 don't just spit out an answer, they burn extra compute at inference time, generating long chains of intermediate steps before committing to a final response. This "test-time reasoning" is why they're so good at math, logic, and multi-step problems. But we only ever watch this process from the outside, reading the output tokens as a model branches, backtracks, or corrects itself. Nobody actually knows what's happening under the hood when it does.

Worse, these models' most dangerous failures aren't hesitant guesses; they're confident, fluent, perfectly-structured chains of reasoning that are just wrong. And the tools we use to catch uncertainty during test-time reasoning, like token entropy, are blind to this exact failure mode, because a confidently wrong model doesn't look uncertain at all.

We're building the first mechanistic interpretability toolkit for test-time reasoning itself. Using sparse autoencoders, the same technique Anthropic used to find interpretable features inside Claude, we're going to crack open models like Qwen-2.5-Math and DeepSeek-R1-Distill while they reason, and find the actual internal circuits behind uncertainty, branching, premise commitment, and error recovery as they unfold step by step. Then we're not just going to observe these features, we're going to causally test them: amplify them, suppress them, and see if we can steer a model toward catching its own mistakes mid-chain, before they cascade into a wrong answer.

This is a research team building real infrastructure (SAELens, TransformerLens, Circuit Tracer), targeting a workshop paper and a top-venue submission. You'll get hands-on experience in one of the most in-demand, least-taught areas of AI safety research, the kind of work that's usually locked inside frontier labs, while actually shipping open-source tools and a diagnostic benchmark the community can use.

If you want to stop treating language models as black boxes and start finding out what's really going on inside them while they think, this is the project.$mechanistic$
    when 'Task-Differentiated EEG Hyperscanning' then $eeg$We are investigating EEG Hyperscanning: how two individual's brain waves synchronize during social interactions. Our framework aims to replicate realistic team settings by assigning participants distinct tasks but a shared goal—diffusing a virtual bomb. This procedure will inform our understanding of how neural synchronization potentially enables social teamwork.

In typical hyperscanning paradigms, we measure neural synchronization on participants who are completing identical tasks. This design has two main limitations we seek to address: (1) it applies poorly to most team settings, since team members tend to differ in tasks; (2) by giving identical tasks, participants are exposed to similar sensory stimuli. When studying the effects of cognitive teamwork on neural synchronization, shared sensory stimuli causes an issue where we cannot tell if the observed effects are due to cognition or sensation. By implementing distinct tasks, we increase our confidence that the observed synchronization is (1) reflective of real-world teamwork; (2) caused by cognitive synchronization.

We are aiming to make two sub-teams within our project, which each require different skill sets. The Research Team will complete literature reviews, write the paper, and run participants through the experimental procedure, and the Coding Team will pre-process and analyze EEG data using machine learning. Both teams will work together to create the experimental procedure to maximize ease of data collection and ability to fill gaps in the literature, as described above. For the Research Team, we want individuals who are adept at reading scientific literature, scientific writing and instructing participants through a procedure. For the Coding Team, we want individuals who have strong coding fundamentals—no previous AI or machine learning experience is needed. Experience with MATLAB, EEG, and EEGLAB is appreciated!$eeg$
    when 'Wildfire Discovery Drone' then $wildfire$Under the supervision of Dr. Siddiqui and Dr. Asad, this project is developing a high-precision, drone-based wildfire detection and satellite validation system!

The team is operating RCMP commercial-grade drones, provided and piloted by professionals at the Royal Military College of Canada, equipped with a FLIR A700-series thermal camera (a $30,000+ research-grade radiometric imaging system) alongside CO, CO₂, and CH₄ gas sensors to capture fine-scale emission and heat signatures over high-risk areas such as farmland. The platform runs a distributed onboard computing architecture: an NVIDIA Jetson handles real-time thermal image acquisition and processing, while a Raspberry Pi 5 manages synchronized gas-sensor data collection, with all streams analyzed in MATLAB. By calibrating UAV measurements against ground-truth sensors and satellite data from sources like NASA, the project aims to validate and correct satellite wildfire detection with sub-pixel precision, transforming early detection into a powerful tool for prevention.$wildfire$
    when 'Diffusion-Model Rendering for Re-Themable Games' then $diffusion$Imagine a Doom-style shooter running live. WASD to move, one button to shoot. Now you type "make this Care Bears" and the walls, the enemies, the entire look of the game change on the spot. No re-downloading assets. No artist rebuilding anything. No coding agent regenerating textures in the background. The game just becomes the new theme while you keep playing.

That is impossible in a traditional engine, because the visuals are baked into hand-built 3D models and textures. Changing the look means rebuilding the assets. A diffusion model sidesteps this entirely. Instead of drawing triangles, it generates each frame directly — the way an image model synthesizes a picture from noise — except conditioned on the game's state and run in a loop, each frame feeding the next. If the look is driven by a prompt or a reference image instead of fixed assets, re-theming stops being an asset pipeline problem and becomes a conditioning problem.

That's the north star. This year, we're going to explore that problem space to see if it's one day feasible.

Further Project Details: https://drive.google.com/file/d/1tptag4-g5bOo2qjKrx6eM_tjnsjF2ngQ/view?usp=sharing$diffusion$
   end
 where p."projectTitle" in (
   'DCP Federated Learning',
   'Conversational Intelligence for Advanced Process Control',
   'TrustLayer',
   'AI Agent Integration',
   'ScamBench AI Recruitment Phishing',
   'Beyond AUROC: Clinical Readiness of ED Chest-Pain AI',
   'LLM-Enhanced Decision Making Agents for Cloud Autoscaling',
   'Uncertainty-Aware Deep Learning for Parkinsonian Motor Symptom Severity Estimation from Monocular Video',
   'CanopyMap',
   'Mechanistic Interpretability of Test-Time Reasoning in Large Language Models',
   'Task-Differentiated EEG Hyperscanning',
   'Wildfire Discovery Drone',
   'Diffusion-Model Rendering for Re-Themable Games'
 );
